version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
      day: "friday"
    cooldown:
      default-days: 3

  - package-ecosystem: "bundler"
    directory: "/slack-unfurling-github"
    schedule:
      interval: "weekly"
      timezone: "Asia/Tokyo"
      day: "friday"
    cooldown:
      default-days: 3
